// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	tools "github.com/wejick/gchain/tools"
)

// BaseExecutor is an autogenerated mock type for the BaseExecutor type
type BaseExecutor struct {
	mock.Mock
}

// RegisterTool provides a mock function with given fields: tool
func (_m *BaseExecutor) RegisterTool(tool *tools.BaseTool) {
	_m.Called(tool)
}

// Run provides a mock function with given fields: ctx, input
func (_m *BaseExecutor) Run(ctx context.Context, input map[string]string) (map[string]string, error) {
	ret := _m.Called(ctx, input)

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) (map[string]string, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) map[string]string); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBaseExecutor creates a new instance of BaseExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBaseExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *BaseExecutor {
	mock := &BaseExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
