// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/wejick/gchain/model"
)

// CombinedDocument is an autogenerated mock type for the CombinedDocument type
type CombinedDocument struct {
	mock.Mock
}

// Combine provides a mock function with given fields: ctx, docs, options
func (_m *CombinedDocument) Combine(ctx context.Context, docs []string, options ...func(*model.Option)) (string, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, docs)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, ...func(*model.Option)) (string, error)); ok {
		return rf(ctx, docs, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, ...func(*model.Option)) string); ok {
		r0 = rf(ctx, docs, options...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, ...func(*model.Option)) error); ok {
		r1 = rf(ctx, docs, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCombinedDocument creates a new instance of CombinedDocument. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCombinedDocument(t interface {
	mock.TestingT
	Cleanup(func())
}) *CombinedDocument {
	mock := &CombinedDocument{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
